Fix logging of where application is bound
gobuffalo/buffalo pull request #2249
Opened 2022-04-25 23:33 UTC by hut8

Addresses https://github.com/gobuffalo/buffalo/issues/2248

This adds a method to a public interface, which isn't ideal and may technically be a breaking change. I'm open to suggestions about that.

2022-04-25 23:45 UTC, hut8 commented
Log message is now:

```
 msg="starting server of type *servers.TLS at 0.0.0.0:443"
```

2022-04-26 15:23 UTC, sio4 requested changes
Thank you for the PR!
I wrote some comments so please kindly consider them.

Briefly, I would like to minimize the changes to the interface since we are now planning a next version and don't want to introduce breaking changes while I fully agreed that the wrong information should be fixed.

2022-04-26 15:25 UTC, sio4 commented on server.go
> -	a.Logger.Infof("starting application at http://%s", a.Options.Addr)
but this is not a critical :-)

2022-04-26 19:48 UTC, hut8 commented on servers/simple.go
> +func (s *Simple) Addr() string {
Great solution 👍🏻 That resolves my main concern

2022-04-26 20:04 UTC, hut8 commented
```
DEBU[2022-04-26T20:02:55Z] starting application
INFO[2022-04-26T20:02:55Z] starting simple server on 0.0.0.0:3000
```
That's the new output.

2022-04-27 12:28 UTC, sio4 approved these changes
Thanks! LGTM

2022-04-27 12:39 UTC, sio4 commented
Hi @paganotoni,
Could you please take a look at this PR and merge it? This PR improved the startup message.
(what happen with the codeclimate? :thinking: )

2022-04-29 19:11 UTC, hut8 commented
Absolutely. My mistake! Thanks for correcting me on that. I'll get this
done today or tomorrow

On Fri, Apr 29, 2022, 10:17 Yonghwan SO ***@***.***> wrote:

> Hi @hut8 <https://github.com/hut8>,
>
> I just realized that this PR is opened against the main branch.
> Currently, all PR requests should open to the development branch. I tried
> to edit the base but it seems like it could break the commit history. Could
> you please check your forked repository/branch or reopen the PR against the
> development branch?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/gobuffalo/buffalo/pull/2249#issuecomment-1113369186>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACYZSB5WSUPFH2T7EEATULVHPVOPANCNFSM5UKCKD3Q>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-04-30 17:07 UTC, paganotoni approved these changes
LGTM!

2022-05-01 13:47 UTC, paganotoni commented
@hut8 thanks for putting together this one. I attempted to rebase it to development but seems it has some conflicts. Can you please take care of those. Thanks again!

2022-05-01 18:21 UTC, hut8 commented
@paganotoni I think I took care of it 😄

2022-05-01 23:48 UTC, merged